[production]
discord_api_key="MTI5NDAxODcxMTY2MDc4OTg4Mg.GmQL4y.0vpa6NgKaaq7jcS4v1MozIZyeT9s_oM9TXvilk"  #discord token

api_key_raid_helper="NjOuUNIJbHiI1bftfSHcLz208LybiYCd2bdSfUCI" #token of ava discord fr


