[development]
discord_api_key="MTI5NDAxODcxMTY2MDc4OTg4Mg.GmQL4y.0vpa6NgKaaq7jcS4v1MozIZyeT9s_oM9TXvilk"  #disxord token



api_key_raid_helper="4mWrXjSvWSY9nd7lNg4RxaMHsKTy1LEkEBaPSrFN" # api_key sur albion_emote_1